name: build apk
on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Set a Tag'
        required: true
        default: ''
  push:
    tags:
      - v*
jobs:
  build:
    name: Release build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Build split apk
        run: |
          \cp -f pubspec.yaml assets/
          ls assets
          flutter pub get
          flutter build apk --release
          flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi --release
          ls build/app/outputs/flutter-apk
          mv -f build/app/outputs/flutter-apk/*-release.apk releases
          ls releases
          mv -f releases/app-release.apk releases/app-universal-release.apk
          ls releases
      - name: Sign build apk
        uses: iota9star/sign-android-release@v1.0.5
        with:
          releaseDirectory: releases
          fileRegex: .*-release.apk
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"
      - name: Rename signed apk
        run: |
          ls releases
          for name in $(ls releases/*-signed.apk);do mv -f $name ${name%-signed.apk}.apk ;done
          ls releases
      - name: Release to github
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*-release.apk"
          token: ${{ secrets.ACTION_TOKEN }}
          tag: ${{ github.event.inputs.TAG }}
      - name: Write meta file
        run: |
          dart scripts/releases.dart
      - name: Commit binary files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":bookmark: Release binary files."
          file_pattern: releases/*-release.apk releases/meta.json

